language: c
os: linux
dist: bionic
group: edge

jobs:
  include:
    - addons:
        apt:
          packages:
            - swig
            - python-dev
            - valgrind
            - libyaml-0-2
      script:
        - make
        - make check && make checkm

    # Check it builds properly without optional packages:
    #     python, valgrind, libyaml
    - script:
        - make
        - make check

    - arch: arm64
      addons:
        apt:
          packages:
            - swig
            - python-dev
            - valgrind
            - libyaml-0-2
      script:
        - make
        - make check checkm

    - arch: ppc64le
      addons:
        apt:
          packages:
            - swig
            - python-dev
            - libyaml-0-2
      script:
        - make
        - make check

    - arch: s390x
      addons:
        apt:
          packages:
            - swig
            - python-dev
            - valgrind
            - libyaml-0-2
      script:
        - make
        - make check checkm
